//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibolEntities : DbContext
    {
        public LibolEntities()
            : base("name=LibolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACQ_ACQUIRE_SOURCE> ACQ_ACQUIRE_SOURCE { get; set; }
        public virtual DbSet<ACQ_BUDGET> ACQ_BUDGET { get; set; }
        public virtual DbSet<ACQ_BUDGET_ACCUMULATE> ACQ_BUDGET_ACCUMULATE { get; set; }
        public virtual DbSet<ACQ_BUDGET_CREDIT> ACQ_BUDGET_CREDIT { get; set; }
        public virtual DbSet<ACQ_BUDGET_DEBIT> ACQ_BUDGET_DEBIT { get; set; }
        public virtual DbSet<ACQ_CURRENCY> ACQ_CURRENCY { get; set; }
        public virtual DbSet<ACQ_ITEM> ACQ_ITEM { get; set; }
        public virtual DbSet<ACQ_ONLOAN_INLIST_INVENT> ACQ_ONLOAN_INLIST_INVENT { get; set; }
        public virtual DbSet<ACQ_PO> ACQ_PO { get; set; }
        public virtual DbSet<ACQ_STATUS> ACQ_STATUS { get; set; }
        public virtual DbSet<ACQ_VENDOR> ACQ_VENDOR { get; set; }
        public virtual DbSet<BANDOC_IN> BANDOC_IN { get; set; }
        public virtual DbSet<Book_code> Book_code { get; set; }
        public virtual DbSet<CAT_AUTHORITY> CAT_AUTHORITY { get; set; }
        public virtual DbSet<CAT_BIBLIOGRAPHY> CAT_BIBLIOGRAPHY { get; set; }
        public virtual DbSet<CAT_BIBLIOGRAPHY_DETAIL> CAT_BIBLIOGRAPHY_DETAIL { get; set; }
        public virtual DbSet<CAT_DIC_AUTHOR> CAT_DIC_AUTHOR { get; set; }
        public virtual DbSet<CAT_DIC_CLASS_BBK> CAT_DIC_CLASS_BBK { get; set; }
        public virtual DbSet<CAT_DIC_CLASS_DDC> CAT_DIC_CLASS_DDC { get; set; }
        public virtual DbSet<CAT_DIC_CLASS_LOC> CAT_DIC_CLASS_LOC { get; set; }
        public virtual DbSet<CAT_DIC_CLASS_NLM> CAT_DIC_CLASS_NLM { get; set; }
        public virtual DbSet<CAT_DIC_CLASS_NSC> CAT_DIC_CLASS_NSC { get; set; }
        public virtual DbSet<CAT_DIC_CLASS_UDC> CAT_DIC_CLASS_UDC { get; set; }
        public virtual DbSet<CAT_DIC_COUNTRY> CAT_DIC_COUNTRY { get; set; }
        public virtual DbSet<CAT_DIC_ITEM_TYPE> CAT_DIC_ITEM_TYPE { get; set; }
        public virtual DbSet<CAT_DIC_KEYWORD> CAT_DIC_KEYWORD { get; set; }
        public virtual DbSet<CAT_DIC_LANGUAGE> CAT_DIC_LANGUAGE { get; set; }
        public virtual DbSet<CAT_DIC_LIST> CAT_DIC_LIST { get; set; }
        public virtual DbSet<CAT_DIC_MEDIUM> CAT_DIC_MEDIUM { get; set; }
        public virtual DbSet<CAT_DIC_OAI_SET> CAT_DIC_OAI_SET { get; set; }
        public virtual DbSet<CAT_DIC_PUBLISHER> CAT_DIC_PUBLISHER { get; set; }
        public virtual DbSet<CAT_DIC_RECORDTYPE> CAT_DIC_RECORDTYPE { get; set; }
        public virtual DbSet<CAT_DIC_RELATOR> CAT_DIC_RELATOR { get; set; }
        public virtual DbSet<CAT_DIC_SER_CATEGORY> CAT_DIC_SER_CATEGORY { get; set; }
        public virtual DbSet<CAT_DIC_SERIES> CAT_DIC_SERIES { get; set; }
        public virtual DbSet<CAT_DIC_SH> CAT_DIC_SH { get; set; }
        public virtual DbSet<CAT_DIC_THESIS_LEVEL> CAT_DIC_THESIS_LEVEL { get; set; }
        public virtual DbSet<CAT_DIC_THESIS_SUBJECT> CAT_DIC_THESIS_SUBJECT { get; set; }
        public virtual DbSet<CAT_EDATA_AUDIO> CAT_EDATA_AUDIO { get; set; }
        public virtual DbSet<CAT_EDATA_COLLECTION> CAT_EDATA_COLLECTION { get; set; }
        public virtual DbSet<CAT_EDATA_FILE> CAT_EDATA_FILE { get; set; }
        public virtual DbSet<CAT_EDATA_IMAGE> CAT_EDATA_IMAGE { get; set; }
        public virtual DbSet<CAT_EDATA_METADATA> CAT_EDATA_METADATA { get; set; }
        public virtual DbSet<CAT_EDATA_METADATA_DEFIN> CAT_EDATA_METADATA_DEFIN { get; set; }
        public virtual DbSet<CAT_EDATA_MULTIMEDIA> CAT_EDATA_MULTIMEDIA { get; set; }
        public virtual DbSet<CAT_EDATA_URL> CAT_EDATA_URL { get; set; }
        public virtual DbSet<CAT_EDATA_VIDEO> CAT_EDATA_VIDEO { get; set; }
        public virtual DbSet<CIR_DIC_COLLEGE> CIR_DIC_COLLEGE { get; set; }
        public virtual DbSet<CIR_DIC_EDUCATION> CIR_DIC_EDUCATION { get; set; }
        public virtual DbSet<CIR_DIC_ETHNIC> CIR_DIC_ETHNIC { get; set; }
        public virtual DbSet<CIR_DIC_FACULTY> CIR_DIC_FACULTY { get; set; }
        public virtual DbSet<CIR_DIC_OCCUPATION> CIR_DIC_OCCUPATION { get; set; }
        public virtual DbSet<CIR_DIC_PROVINCE> CIR_DIC_PROVINCE { get; set; }
        public virtual DbSet<CIR_FINE> CIR_FINE { get; set; }
        public virtual DbSet<CIR_HOLDING> CIR_HOLDING { get; set; }
        public virtual DbSet<CIR_LOAN> CIR_LOAN { get; set; }
        public virtual DbSet<CIR_LOAN_HISTORY> CIR_LOAN_HISTORY { get; set; }
        public virtual DbSet<CIR_LOAN_TYPE> CIR_LOAN_TYPE { get; set; }
        public virtual DbSet<CIR_PATRON> CIR_PATRON { get; set; }
        public virtual DbSet<CIR_PATRON_BLOCK> CIR_PATRON_BLOCK { get; set; }
        public virtual DbSet<CIR_PATRON_GROUP> CIR_PATRON_GROUP { get; set; }
        public virtual DbSet<CIR_PATRON_LOCK> CIR_PATRON_LOCK { get; set; }
        public virtual DbSet<CIR_PATRON_OTHER_ADDR> CIR_PATRON_OTHER_ADDR { get; set; }
        public virtual DbSet<CIR_PATRON_UNIVERSITY> CIR_PATRON_UNIVERSITY { get; set; }
        public virtual DbSet<CIR_PHOTOCOPY_PRICE> CIR_PHOTOCOPY_PRICE { get; set; }
        public virtual DbSet<CIR_PHOTOCOPY_REQUEST> CIR_PHOTOCOPY_REQUEST { get; set; }
        public virtual DbSet<CIR_PRINTED_CARD> CIR_PRINTED_CARD { get; set; }
        public virtual DbSet<CIR_RENEW> CIR_RENEW { get; set; }
        public virtual DbSet<CIR_RESERVE_REQUEST> CIR_RESERVE_REQUEST { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATIONs { get; set; }
        public virtual DbSet<CLASSIFICATION_FIELD> CLASSIFICATION_FIELD { get; set; }
        public virtual DbSet<CLASSIFICATION_LINK_TYPES> CLASSIFICATION_LINK_TYPES { get; set; }
        public virtual DbSet<CLASSIFICATION_LINKS> CLASSIFICATION_LINKS { get; set; }
        public virtual DbSet<DICTIONARY40> DICTIONARY40 { get; set; }
        public virtual DbSet<DICTIONARY41> DICTIONARY41 { get; set; }
        public virtual DbSet<DICTIONARY42> DICTIONARY42 { get; set; }
        public virtual DbSet<DICTIONARY43> DICTIONARY43 { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<EDELIV_FILE> EDELIV_FILE { get; set; }
        public virtual DbSet<EDELIV_PAYMENT> EDELIV_PAYMENT { get; set; }
        public virtual DbSet<EDELIV_REQUEST> EDELIV_REQUEST { get; set; }
        public virtual DbSet<EDELIV_REQUEST_MODE> EDELIV_REQUEST_MODE { get; set; }
        public virtual DbSet<EDELIV_STATUS> EDELIV_STATUS { get; set; }
        public virtual DbSet<EDELIV_USER> EDELIV_USER { get; set; }
        public virtual DbSet<FIELD_AUTHORITY> FIELD_AUTHORITY { get; set; }
        public virtual DbSet<FIELD000S> FIELD000S { get; set; }
        public virtual DbSet<FIELD100S> FIELD100S { get; set; }
        public virtual DbSet<FIELD200S> FIELD200S { get; set; }
        public virtual DbSet<FIELD300S> FIELD300S { get; set; }
        public virtual DbSet<FIELD400S> FIELD400S { get; set; }
        public virtual DbSet<FIELD500S> FIELD500S { get; set; }
        public virtual DbSet<FIELD600S> FIELD600S { get; set; }
        public virtual DbSet<FIELD700S> FIELD700S { get; set; }
        public virtual DbSet<FIELD800S> FIELD800S { get; set; }
        public virtual DbSet<FIELD900S> FIELD900S { get; set; }
        public virtual DbSet<HELP_CAT_DIC> HELP_CAT_DIC { get; set; }
        public virtual DbSet<HELP_CAT_FILE> HELP_CAT_FILE { get; set; }
        public virtual DbSet<HELP_DIC_ITEM> HELP_DIC_ITEM { get; set; }
        public virtual DbSet<HELP_ITEM_LINK> HELP_ITEM_LINK { get; set; }
        public virtual DbSet<HOLDING> HOLDINGs { get; set; }
        public virtual DbSet<HOLDING_INVENTORY> HOLDING_INVENTORY { get; set; }
        public virtual DbSet<HOLDING_LIBRARY> HOLDING_LIBRARY { get; set; }
        public virtual DbSet<HOLDING_LOCATION> HOLDING_LOCATION { get; set; }
        public virtual DbSet<HOLDING_LOCATION_PROCESS> HOLDING_LOCATION_PROCESS { get; set; }
        public virtual DbSet<HOLDING_LOCATION_SCHEMA> HOLDING_LOCATION_SCHEMA { get; set; }
        public virtual DbSet<HOLDING_REMOVE_REASON> HOLDING_REMOVE_REASON { get; set; }
        public virtual DbSet<HOLDING_REMOVED> HOLDING_REMOVED { get; set; }
        public virtual DbSet<HOLDING_SHELF_SCHEMA> HOLDING_SHELF_SCHEMA { get; set; }
        public virtual DbSet<ILL_APDU_TYPES> ILL_APDU_TYPES { get; set; }
        public virtual DbSet<ILL_COPYRIGHT_COMPLIANCE> ILL_COPYRIGHT_COMPLIANCE { get; set; }
        public virtual DbSet<ILL_INCOMING_REQUESTS> ILL_INCOMING_REQUESTS { get; set; }
        public virtual DbSet<ILL_INCOMING_REQUESTS_BILINF> ILL_INCOMING_REQUESTS_BILINF { get; set; }
        public virtual DbSet<ILL_INCOMING_REQUESTS_DELINF> ILL_INCOMING_REQUESTS_DELINF { get; set; }
        public virtual DbSet<ILL_INCOMING_REQUESTS_DENIED> ILL_INCOMING_REQUESTS_DENIED { get; set; }
        public virtual DbSet<ILL_INCOMING_REQUESTS_LOG> ILL_INCOMING_REQUESTS_LOG { get; set; }
        public virtual DbSet<ILL_ITEM_TYPES> ILL_ITEM_TYPES { get; set; }
        public virtual DbSet<ILL_LIBRARIES> ILL_LIBRARIES { get; set; }
        public virtual DbSet<ILL_LOCAL_LIBRARY_ADDRESSES> ILL_LOCAL_LIBRARY_ADDRESSES { get; set; }
        public virtual DbSet<ILL_LOCAL_LIBRARY_E_ADDRESSES> ILL_LOCAL_LIBRARY_E_ADDRESSES { get; set; }
        public virtual DbSet<ILL_MEDIUM_TYPES> ILL_MEDIUM_TYPES { get; set; }
        public virtual DbSet<ILL_OUTGOING_REQUESTS> ILL_OUTGOING_REQUESTS { get; set; }
        public virtual DbSet<ILL_OUTGOING_REQUESTS_DENIED> ILL_OUTGOING_REQUESTS_DENIED { get; set; }
        public virtual DbSet<ILL_OUTGOING_REQUESTS_LOG> ILL_OUTGOING_REQUESTS_LOG { get; set; }
        public virtual DbSet<ILL_OUTGOING_REQUESTS_RETINF> ILL_OUTGOING_REQUESTS_RETINF { get; set; }
        public virtual DbSet<ILL_PAYMENT_TYPES> ILL_PAYMENT_TYPES { get; set; }
        public virtual DbSet<ILL_PHYSICAL_DELIVERY_MODES> ILL_PHYSICAL_DELIVERY_MODES { get; set; }
        public virtual DbSet<ILL_REQUEST_ITEMS> ILL_REQUEST_ITEMS { get; set; }
        public virtual DbSet<ILL_REQUEST_STATUS> ILL_REQUEST_STATUS { get; set; }
        public virtual DbSet<ILL_RESPONSES> ILL_RESPONSES { get; set; }
        public virtual DbSet<ILL_SERVICE_TYPES> ILL_SERVICE_TYPES { get; set; }
        public virtual DbSet<ILL_Z3950_DBS> ILL_Z3950_DBS { get; set; }
        public virtual DbSet<ILL_Z3950_SERVERS> ILL_Z3950_SERVERS { get; set; }
        public virtual DbSet<INIT_INVENTORY> INIT_INVENTORY { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<ITEM_FULLTEXT> ITEM_FULLTEXT { get; set; }
        public virtual DbSet<ITEM_ITEM> ITEM_ITEM { get; set; }
        public virtual DbSet<ITEM_TITLE> ITEM_TITLE { get; set; }
        public virtual DbSet<ItemCode> ItemCodes { get; set; }
        public virtual DbSet<MARC_AUTHORITY_BLOCK> MARC_AUTHORITY_BLOCK { get; set; }
        public virtual DbSet<MARC_AUTHORITY_FIELD> MARC_AUTHORITY_FIELD { get; set; }
        public virtual DbSet<MARC_AUTHORITY_FIELD_TYPE> MARC_AUTHORITY_FIELD_TYPE { get; set; }
        public virtual DbSet<MARC_AUTHORITY_INDICATOR> MARC_AUTHORITY_INDICATOR { get; set; }
        public virtual DbSet<MARC_AUTHORITY_WORKSHEET> MARC_AUTHORITY_WORKSHEET { get; set; }
        public virtual DbSet<MARC_BIB_BLOCK> MARC_BIB_BLOCK { get; set; }
        public virtual DbSet<MARC_BIB_FIELD> MARC_BIB_FIELD { get; set; }
        public virtual DbSet<MARC_BIB_INDICATOR> MARC_BIB_INDICATOR { get; set; }
        public virtual DbSet<MARC_FIELD_TYPE> MARC_FIELD_TYPE { get; set; }
        public virtual DbSet<MARC_FUNCTION> MARC_FUNCTION { get; set; }
        public virtual DbSet<MARC_LINK_TYPE> MARC_LINK_TYPE { get; set; }
        public virtual DbSet<MARC_WORKSHEET> MARC_WORKSHEET { get; set; }
        public virtual DbSet<OAI_SET> OAI_SET { get; set; }
        public virtual DbSet<OAI_URL_RESOURCE> OAI_URL_RESOURCE { get; set; }
        public virtual DbSet<OPAC_COMMENT> OPAC_COMMENT { get; set; }
        public virtual DbSet<OPAC_SUBJECT_BBK> OPAC_SUBJECT_BBK { get; set; }
        public virtual DbSet<OPAC_SUBJECT_DDC> OPAC_SUBJECT_DDC { get; set; }
        public virtual DbSet<REGULARITY_OUT> REGULARITY_OUT { get; set; }
        public virtual DbSet<SER_ARTICLE> SER_ARTICLE { get; set; }
        public virtual DbSet<SER_CATEGORY> SER_CATEGORY { get; set; }
        public virtual DbSet<SER_COPY> SER_COPY { get; set; }
        public virtual DbSet<SER_ISSUE> SER_ISSUE { get; set; }
        public virtual DbSet<SER_ITEM> SER_ITEM { get; set; }
        public virtual DbSet<SER_REGULARITY> SER_REGULARITY { get; set; }
        public virtual DbSet<SER_ROUTING> SER_ROUTING { get; set; }
        public virtual DbSet<SER_SUBJECT> SER_SUBJECT { get; set; }
        public virtual DbSet<SYS_EVENT_GROUP> SYS_EVENT_GROUP { get; set; }
        public virtual DbSet<SYS_LOG> SYS_LOG { get; set; }
        public virtual DbSet<SYS_MODULE> SYS_MODULE { get; set; }
        public virtual DbSet<SYS_PARAMETER> SYS_PARAMETER { get; set; }
        public virtual DbSet<SYS_REFERENCE> SYS_REFERENCE { get; set; }
        public virtual DbSet<SYS_TEMP_CODE> SYS_TEMP_CODE { get; set; }
        public virtual DbSet<SYS_TEMP_FILE> SYS_TEMP_FILE { get; set; }
        public virtual DbSet<SYS_TEMPLATE> SYS_TEMPLATE { get; set; }
        public virtual DbSet<SYS_USER> SYS_USER { get; set; }
        public virtual DbSet<SYS_USER_RIGHT> SYS_USER_RIGHT { get; set; }
        public virtual DbSet<SYS_USER_RIGHT_DETAIL> SYS_USER_RIGHT_DETAIL { get; set; }
        public virtual DbSet<SYS_VIEW> SYS_VIEW { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<usertest> usertests { get; set; }
        public virtual DbSet<ACQ_PO_STATUS> ACQ_PO_STATUS { get; set; }
        public virtual DbSet<BOOKCODE_RES> BOOKCODE_RES { get; set; }
        public virtual DbSet<CAT_AUTHORITY_LINK> CAT_AUTHORITY_LINK { get; set; }
        public virtual DbSet<CAT_DIC_DIRLEVEL> CAT_DIC_DIRLEVEL { get; set; }
        public virtual DbSet<CAT_DIC_NUMBER> CAT_DIC_NUMBER { get; set; }
        public virtual DbSet<CAT_DIC_YEAR> CAT_DIC_YEAR { get; set; }
        public virtual DbSet<CAT_EDATA_PARAMETER> CAT_EDATA_PARAMETER { get; set; }
        public virtual DbSet<CAT_QUEUE> CAT_QUEUE { get; set; }
        public virtual DbSet<CIR_OPEN_HOUR> CIR_OPEN_HOUR { get; set; }
        public virtual DbSet<CIR_SERIAL_COUNT> CIR_SERIAL_COUNT { get; set; }
        public virtual DbSet<HOLDING_COPY> HOLDING_COPY { get; set; }
        public virtual DbSet<INVENTORY_COPY> INVENTORY_COPY { get; set; }
        public virtual DbSet<ITEM_AUTHOR> ITEM_AUTHOR { get; set; }
        public virtual DbSet<ITEM_AUTHORITY> ITEM_AUTHORITY { get; set; }
        public virtual DbSet<ITEM_BBK> ITEM_BBK { get; set; }
        public virtual DbSet<ITEM_COUNTRY> ITEM_COUNTRY { get; set; }
        public virtual DbSet<ITEM_DDC> ITEM_DDC { get; set; }
        public virtual DbSet<ITEM_DICTIONARY40> ITEM_DICTIONARY40 { get; set; }
        public virtual DbSet<ITEM_DICTIONARY41> ITEM_DICTIONARY41 { get; set; }
        public virtual DbSet<ITEM_DICTIONARY42> ITEM_DICTIONARY42 { get; set; }
        public virtual DbSet<ITEM_DICTIONARY43> ITEM_DICTIONARY43 { get; set; }
        public virtual DbSet<ITEM_KEYWORD> ITEM_KEYWORD { get; set; }
        public virtual DbSet<ITEM_LANGUAGE> ITEM_LANGUAGE { get; set; }
        public virtual DbSet<ITEM_LIBRARY> ITEM_LIBRARY { get; set; }
        public virtual DbSet<ITEM_LINK> ITEM_LINK { get; set; }
        public virtual DbSet<ITEM_LOC> ITEM_LOC { get; set; }
        public virtual DbSet<ITEM_NLM> ITEM_NLM { get; set; }
        public virtual DbSet<ITEM_NSC> ITEM_NSC { get; set; }
        public virtual DbSet<ITEM_OAI_SET> ITEM_OAI_SET { get; set; }
        public virtual DbSet<ITEM_PUBLISHER> ITEM_PUBLISHER { get; set; }
        public virtual DbSet<ITEM_SERIES> ITEM_SERIES { get; set; }
        public virtual DbSet<ITEM_SH> ITEM_SH { get; set; }
        public virtual DbSet<ITEM_THESIS_SUBJECT> ITEM_THESIS_SUBJECT { get; set; }
        public virtual DbSet<ITEM_UDC> ITEM_UDC { get; set; }
        public virtual DbSet<MARC_AUTHORITY_WS_DETAIL> MARC_AUTHORITY_WS_DETAIL { get; set; }
        public virtual DbSet<MARC_BIB_WS_DETAIL> MARC_BIB_WS_DETAIL { get; set; }
    }
}
